TEAM_FLAGS = {
    "Alemania": "🇩🇪",
    "Arabia Saudita": "🇸🇦",
    "Argelia": "🇩🇿",
    "Argentina": "🇦🇷",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Belgica": "🇧🇪",
    "Bélgica": "🇧🇪",
    "Bosnia y Herzegovina": "🇧🇦",
    "Brasil": "🇧🇷",
    "Cabo Verde": "🇨🇻",
    "Canada": "🇨🇦",
    "Canadá": "🇨🇦",
    "Catar": "🇶🇦",
    "Colombia": "🇨🇴",
    "Corea del Sur": "🇰🇷",
    "Costa de Marfil": "🇨🇮",
    "Croacia": "🇭🇷",
    "Curazao": "🇨🇼",
    "Ecuador": "🇪🇨",
    "Egipto": "🇪🇬",
    "Escocia": "🏴",
    "Espana": "🇪🇸",
    "España": "🇪🇸",
    "Estados Unidos": "🇺🇸",
    "Francia": "🇫🇷",
    "Ghana": "🇬🇭",
    "Haiti": "🇭🇹",
    "Haití": "🇭🇹",
    "Inglaterra": "🇬🇧",
    "Irak": "🇮🇶",
    "Iran": "🇮🇷",
    "Irán": "🇮🇷",
    "Japon": "🇯🇵",
    "Japón": "🇯🇵",
    "Jordania": "🇯🇴",
    "Marruecos": "🇲🇦",
    "Mexico": "🇲🇽",
    "México": "🇲🇽",
    "Noruega": "🇳🇴",
    "Nueva Zelanda": "🇳🇿",
    "Paises Bajos": "🇳🇱",
    "Países Bajos": "🇳🇱",
    "Panama": "🇵🇦",
    "Panamá": "🇵🇦",
    "Paraguay": "🇵🇾",
    "Portugal": "🇵🇹",
    "RD Congo": "🇨🇩",
    "Republica Checa": "🇨🇿",
    "República Checa": "🇨🇿",
    "Senegal": "🇸🇳",
    "Sudafrica": "🇿🇦",
    "Sudáfrica": "🇿🇦",
    "Suecia": "🇸🇪",
    "Suiza": "🇨🇭",
    "Tunez": "🇹🇳",
    "Túnez": "🇹🇳",
    "Turquia": "🇹🇷",
    "Turquía": "🇹🇷",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Uzbekistán": "🇺🇿",
}


def team_flag(team_name):
    if not team_name:
        return "🏆"
    if any(term in team_name for term in ("Clasificado", "Ganador", "Perdedor")):
        return "🏆"
    return TEAM_FLAGS.get(team_name, "🏳️")
